name: nemocheck_env
channels:
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - cdo         
  - cartopy
  - dash
  - dash-bootstrap-components
  - matplotlib
  - numpy
  - pandas
  - plotly
  - regionmask
  - eofs
  - scipy
  - xarray
  - xesmf >=0.8.0
  - netCDF4
  - pyproj  
  - proj
  - pip   
